<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3228e41886314be4786e8da3ca100d2b
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Monica\\JvyComposer\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Monica\\JvyComposer\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3228e41886314be4786e8da3ca100d2b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3228e41886314be4786e8da3ca100d2b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3228e41886314be4786e8da3ca100d2b::$classMap;

        }, null, ClassLoader::class);
    }
}
